name: Release Documentation
on:
  workflow_dispatch:
    inputs:
      documentation-version:
        description: 'The version of documentation you want to deploy (e.g., 4.9.1), for docu the version will be used as 4.9.x'
        required: true
      set-default:
        description: 'Set as default documentation version'
        required: false
        default: 'true'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Fetch gh-pages branch if exists
        run: |
  
          if ! git ls-remote --exit-code origin gh-pages; then
            echo "gh-pages branch does NOT exist. Skipping fetch."
          else
            git fetch origin gh-pages:gh-pages
          fi

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v5
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Derive minor wildcard version
        run: |
          DOC_VERSION="${{ inputs.documentation-version }}"
          DOC_VERSION_X="${DOC_VERSION%.*}.x"
          echo "DOC_VERSION_X=$DOC_VERSION_X" >> $GITHUB_ENV

      - run: pip install mkdocs-material mike
      - run: pip install mkdocs-print-site-plugin
      - run: mike deploy --push --update-aliases ${DOC_VERSION_X} latest
      - run: |                      # set default only if gh-pages branch does not exists
          if [ "${{ inputs.set-default }}" = "true" ]; then  
            mike set-default latest --push
          fi
          

  tag-repo:
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write   # REQUIRED to push tags

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0   # required so tags/history exist

      - name: Create and push tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          
          git tag ${{ inputs.documentation-version }}
          git push origin ${{ inputs.documentation-version }}

      
          
